routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('students', 'StudentController');

Route::resource('users', 'UserController');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = ['name', 'birthdate'];
    protected $guared = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Student;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $students = Student::orderBy('id', 'desc')->paginate(20);
        return view('students.index', ['students' => $students]);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::orderBy('id', 'desc')->paginate(20);
        return view('students.index', ['students' => $students]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|min:3',
            'birthdate' => 'required|min:8'
        ]);
        Student::create([
            'name' => $request->name,
            'birthdate' => $request->birthdate,
        ]);
        return redirect(route('students.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        return view('students.show', ['student' => $student]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return view('students.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        $student->name = $request->name;
        $student->birthdate = $request->birthdate;
        $student->save();
        session()->flash('message', 'Aluno atualizado com sucesso!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect(route('students.index'));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id', 'desc')->paginate(20);
        return view('users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->name = $request->name;
        $user->username = $request->username;
        $user->email = $request->email;
        $user->save();
        session()->flash('message', 'Usuário atualizado com sucesso!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect(route('users.index'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Unu Acadêmico</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Unu Acadêmico
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registrar') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Unu Acadêmico</title>
    <link rel="stylesheet" href="/css/bootstrap.css">
</head>
<body>
    <div class="bg-info text-white p-5 mb-3">
        <a href="{{ route('students.index')}}" class="btn btn-secondary">Home</a>
        <a href="{{ route('students.create')}}" class="btn btn-secondary">Cadastro de Alunos</a>
        <a href="{{ route('users.index')}}" class="btn btn-secondary">Listagem Usuários</a>
        @auth
    <form class="d-inline-block float-right" action="{{route('logout')}}" method="POST">
                @csrf
    <button type="submit" class="btn btn-secondary">{{auth()->user()->name}} | Logout</button>
            </form>
        @else
            <a href="{{route('login')}}" class="btn btn-secondary">Login</a>
        @endauth
    </div>
    <div class="container">
        @yield('content')
    </div>
    <div class="bg-dark text-white p-4 text-center">
        All rights reserved Ivanildo Lopes {{date('Y')}}.
    </div>
</body>
</html>

resources/views/students/create.blade.php
@extends('master')

@section('content')
    <h2 class="my-3">Adicionar Aluno</h2>
    @if ($errors->all())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </div>
    @endif
    <form action="{{route('students.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="name">Nome</label>
            <input type="text" name="name" id="name" class="form-control">
        </div>
        <div class="form-group">
            <label for="birthdate">Data Nascimento</label>
            <input type="date" name="birthdate" id="birthdate" class="form-control w-25 p-2">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Adicionar Aluno</button>
        </div>
    </form>
@endsection

resources/views/students/edit.blade.php
@extends('master')

@section('content')
    <h2 class="my-3">Atualização de Aluno</h2>
    @if ($errors->all())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </div>
    @endif

    @if (session()->has('message'))
        <div class="alert alert-success">
            {{session()->get('message')}}
        </div>
    @endif

    <form action="{{route('students.update', $student->id)}}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
        <label for="name">Nome</label>
            <input type="text" name="name" id="name" class="form-control" value='{{$student->name}}'>
        </div>
        <div class="form-group">
            <label for="birthdate">Data de Nascimento</label>
            <input type="date" name="birthdate" id="birthdate" class="form-control w-25 p-2" value="{{$student->birthdate}}">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Atualizar Aluno</button>
        </div>
    </form>
@endsection

resources/views/students/index.blade.php
@extends('master')

@section('content')
        <h1>Todos Alunos</h1>
        @foreach ($students as $student)
            <div class="card mt-4">
                <div class="card-body">
                    <h2>
                        <a href="{{ route('students.show', $student->id)}}">
                            {{$student->name}}
                        </a>
                        <a href="{{route('students.edit', $student->id)}}" class="btn btn-info">Editar</a>
                        <form onsubmit="return confirm('Realmente deseja deletar o aluno?')" class="d-inline-block" action="{{route('students.destroy', $student->id)}}" method="POST">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-danger">Deletar</button>
                        </form>
                    </h2>
                </div>
            </div>
        @endforeach
        <div class="mt-4">
            {{$students ?? ''->links()}}
        </div>
@endsection

resources/views/students/show.blade.php
@extends('master')

@section('content')
    <div class="card">
        <div class="card-header">
            <h1 class="text-center">Detalhes dos alunos</h1>
        </div>
        <div class="card-header">
            <h2>Nome: {{$student->name}}</h2>
        </div>
        <div class="card-body">
            <p>Data de Aniversário: {{$student->birthdate}}</p>
        </div>
    </div>
@stop

resources/views/users/edit.blade.php
@extends('master')

@section('content')
    <h2 class="my-3">Atualização de Usuários</h2>
    @if ($errors->all())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </div>
    @endif

    @if (session()->has('message'))
        <div class="alert alert-success">
            {{session()->get('message')}}
        </div>
    @endif

    <form action="{{route('users.update', $user->id)}}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
        <label for="name">Nome</label>
            <input type="text" name="name" id="name" class="form-control" value='{{$user->name}}'>
        </div>
        <div class="form-group">
            <label for="username">Username</label>
                <input type="text" name="username" id="username" class="form-control" value='{{$user->username}}'>
            </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" name="email" id="email" class="form-control" value="{{$user->email}}">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Atualizar Usuário</button>
        </div>
    </form>
@endsection

resources/views/users/index.blade.php
@extends('master')

@section('content')
        <h1>Todos Usuários</h1>
        @foreach ($users as $user)
            <div class="card mt-4">
                <div class="card-body">
                    <h2>
                        <a href="{{ route('users.show', $user->id)}}">
                            {{$user->name}}
                        </a>
                        <a href="{{route('users.edit', $user->id)}}" class="btn btn-info">Editar</a>
                        <form onsubmit="return confirm('Realmente deseja deletar o Usuário?')" class="d-inline-block" action="{{route('users.destroy', $user->id)}}" method="POST">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-danger">Deletar</button>
                        </form>
                    </h2>
                </div>
            </div>
        @endforeach
        <div class="mt-4">
            {{$users ?? ''->links()}}
        </div>
@endsection

resources/views/users/show.blade.php
@extends('master')

@section('content')
    <div class="card">
        <div class="card-header">
            <h1 class="text-center">Detalhes dos Usuários</h1>
        </div>
        <div class="card-header">
            <h2>Nome: {{$user->name}}</h2>
        </div>
        <div class="card-body">
            <p>Username: {{$user->username}}</p>
        </div>
        <div class="card-body">
            <p>Email: {{$user->email}}</p>
        </div>
    </div>
@stop